# Generated by Django 5.1.15 on 2026-05-25 11:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (English)')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='الشعار')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5, verbose_name='نسبة الضريبة الافتراضية %')),
                ('currency_code', models.CharField(default='EGP', max_length=8, verbose_name='العملة')),
            ],
            options={
                'verbose_name': 'بيانات الشركة',
                'verbose_name_plural': 'بيانات الشركة',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الحساب')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (English)')),
                ('account_type', models.CharField(choices=[('ASSET', 'أصول'), ('LIABILITY', 'خصوم'), ('EQUITY', 'حقوق ملكية'), ('REVENUE', 'إيرادات'), ('EXPENSE', 'مصروفات')], max_length=20, verbose_name='النوع')),
                ('is_group', models.BooleanField(default=False, verbose_name='حساب رئيسي (تجميعي)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='البيان')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('CANCELLED', 'ملغي')], default='POSTED', max_length=10, verbose_name='الحالة')),
                ('source_doc_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المستند')),
                ('source_doc_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المستند')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي الدائن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='دائن')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='البيان')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.account')),
            ],
            options={
                'verbose_name': 'بند قيد',
                'verbose_name_plural': 'بنود القيود',
            },
        ),
    ]
