# Generated by Django 5.1.15 on 2026-05-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='fabric_dyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='manufacturing.fabricdyer', verbose_name='المصبغة'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='fabric_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='manufacturing.fabricsupplier', verbose_name='مورد القماش'),
        ),
    ]
