# Generated by Django 5.1.15 on 2026-05-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_journalline_fabric_dyer_journalline_fabric_supplier'),
        ('manufacturing', '0003_supplier_vendortype_alter_fabricbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='manufacturing.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='fabric_dyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='manufacturing.fabricdyer', verbose_name='المصبغة (legacy)'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='fabric_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='manufacturing.fabricsupplier', verbose_name='مورد القماش (legacy)'),
        ),
    ]
