# Generated by Django 5.1.15 on 2026-05-30 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_drop_legacy_vendor_fks'),
        ('manufacturing', '0026_alter_productionorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: خزينة المحل، الأهلي - جاري، فودافون كاش', max_length=120, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('CASH', 'نقدية (خزينة)'), ('BANK', 'حساب بنكي'), ('WALLET', 'محفظة إلكترونية')], default='BANK', max_length=10, verbose_name='النوع')),
                ('bank_name', models.CharField(blank=True, help_text='مثال: البنك الأهلي المصري، فودافون كاش، إنستاباي', max_length=120, verbose_name='اسم البنك / مزود المحفظة')),
                ('account_number', models.CharField(blank=True, max_length=60, verbose_name='رقم الحساب / المحفظة')),
                ('is_default', models.BooleanField(default=False, help_text='بيُقترح تلقائياً في السندات الجديدة', verbose_name='الحساب الافتراضي')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_account', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_account', to='core.account', verbose_name='حساب دليل الحسابات')),
            ],
            options={
                'verbose_name': 'حساب نقدية/بنك/محفظة',
                'verbose_name_plural': 'حسابات النقدية والبنوك والمحافظ',
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=120, unique=True, verbose_name='اسم البند')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('gl_account', models.ForeignKey(limit_choices_to={'account_type': 'EXPENSE', 'is_group': False}, on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='core.account', verbose_name='حساب المصروف')),
            ],
            options={
                'verbose_name': 'بند مصروف',
                'verbose_name_plural': 'بنود المصروفات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (EXP-0001 ...)', max_length=30, unique=True, verbose_name='رقم السند')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(blank=True, help_text='تفاصيل المصروف — مثال: مرتب شهر 5، إيجار المحل', max_length=300, verbose_name='البيان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_vouchers', to='core.cashaccount', verbose_name='مدفوع من (نقدية/بنك/محفظة)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='core.expensecategory', verbose_name='بند المصروف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'سند صرف مصروف',
                'verbose_name_plural': 'سندات صرف المصروفات',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (FA-0001 ...)', max_length=30, unique=True, verbose_name='رقم الأصل')),
                ('name', models.CharField(help_text='مثال: ماكينة أوفر لوك، لاب توب Dell، سيارة نقل', max_length=200, verbose_name='اسم الأصل')),
                ('category', models.CharField(choices=[('FURNITURE', 'أثاث ومفروشات'), ('MACHINERY', 'آلات ومعدات'), ('COMPUTER', 'أجهزة وكمبيوتر'), ('VEHICLE', 'سيارات ووسائل نقل'), ('OTHER', 'أصول ثابتة أخرى')], default='MACHINERY', max_length=12, verbose_name='الفئة')),
                ('acquisition_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='التكلفة')),
                ('payment_method', models.CharField(choices=[('CASH', 'مدفوع (نقدية/بنك/محفظة)'), ('CREDIT', 'آجل (على مورد)')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='المكان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(blank=True, help_text='إجباري لو طريقة الدفع = مدفوع', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_purchases', to='core.cashaccount', verbose_name='مدفوع من (لو نقدي)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('supplier', models.ForeignKey(blank=True, help_text='إجباري لو طريقة الدفع = آجل', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_purchases', to='manufacturing.supplier', verbose_name='المورد (لو آجل)')),
            ],
            options={
                'verbose_name': 'أصل ثابت',
                'verbose_name_plural': 'الأصول الثابتة',
                'ordering': ['-acquisition_date', '-id'],
            },
        ),
    ]
