# Generated by Django 5.1.15 on 2026-05-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_mfg_wage_variance_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='supplier_invoice_no',
            field=models.CharField(blank=True, help_text='لو اشتريت أكتر من أصل (مكن/معدات) على نفس فاتورة المورد، اكتب نفس الرقم في كل أصل عشان تعرف إنهم مع بعض', max_length=50, verbose_name='رقم فاتورة المورد'),
        ),
    ]
