# Generated by Django 5.1.15 on 2026-06-12 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fixedasset_supplier_invoice_no'),
        ('manufacturing', '0040_remove_accessory_waste_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='manufacturing.accessory', verbose_name='الإكسسوار'),
        ),
    ]
