# Generated by Django 5.1.15 on 2026-05-25 11:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (ITM-0001, ITM-0002 ...)', max_length=20, unique=True, verbose_name='كود الموديل')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (English)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='الفئة')),
                ('fabric', models.CharField(blank=True, help_text='مثال: قطن 100%، بوليستر، حرير، صوف، خليط', max_length=100, verbose_name='الخامة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='سعر القائمة قبل خصم الجملة (لكل قطعة)', max_digits=12, verbose_name='السعر الأساسي')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='سعر القطعة بعد خصم الجملة 10%', max_digits=12, verbose_name='سعر القطعة للجملة')),
                ('pack_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='السعر الافتراضي للمجموعة (Pack/Bundle) على فاتورة المبيعات. إذا تركته صفر، النظام يحسبه = سعر القطعة × عدد المقاسات. يمكن للمستخدم تعديل السعر على البند داخل أي فاتورة.', max_digits=14, verbose_name='سعر المجموعة (الباك)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='الصورة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='مقاس حر — مثال: S, M, L, XL, XXL أو 10, 12, 14, 16', max_length=10, verbose_name='المقاس')),
                ('sku_code', models.CharField(blank=True, max_length=40, unique=True, verbose_name='كود SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='الباركود')),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الرصيد الحالي')),
                ('average_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='متوسط التكلفة')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='حد إعادة الطلب')),
                ('size_order', models.PositiveSmallIntegerField(default=999, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'الـ SKUs',
                'ordering': ['item__code', 'size_order'],
                'unique_together': {('item', 'size')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('movement_type', models.CharField(choices=[('OPENING', 'رصيد افتتاحي'), ('PURCHASE_IN', 'إدخال مشتريات'), ('SALES_OUT', 'صرف مبيعات'), ('SALES_RETURN_IN', 'مرتجع مبيعات'), ('PURCHASE_RETURN_OUT', 'مرتجع مشتريات'), ('ADJUST_IN', 'تسوية موجبة'), ('ADJUST_OUT', 'تسوية سالبة'), ('WASTE', 'هالك / تالف')], max_length=30, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='للحركات الواردة فقط (تستخدم في حساب متوسط التكلفة)', max_digits=12, verbose_name='تكلفة الوحدة')),
                ('document_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المستند')),
                ('document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المستند')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.itemvariant', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['variant', 'date'], name='inventory_s_variant_cd3f85_idx'), models.Index(fields=['document_type', 'document_id'], name='inventory_s_documen_60ee97_idx')],
            },
        ),
    ]
