# Generated by Django 5.1.15 on 2026-05-25 16:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dozen_size',
            field=models.PositiveSmallIntegerField(default=12, help_text='الدستة = الوحدة الافتراضية للبيع. مقاس واحد فيها 12 قطعة عادة.', verbose_name='عدد القطع في الدستة'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='سعر بيع القطعة الواحدة من المقاس ده. سعر الدستة = ده × عدد القطع في الدستة.', max_digits=12, verbose_name='سعر البيع (للقطعة)'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='لما الرصيد ينزل عن العدد ده من الدستات، يبقى وقت تطلب تاني.', max_digits=12, verbose_name='حد إعادة الطلب (بالدستة)'),
        ),
    ]
