# Generated by Django 5.1.15 on 2026-05-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_dozen_size_itemvariant_selling_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pack_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wholesale_price',
        ),
    ]
