# Generated by Django 5.1.15 on 2026-05-30 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_base_price_remove_item_pack_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (PRD-0001, PRD-0002 ...)', max_length=20, unique=True, verbose_name='كود المنتج')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (English)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='الفئة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['code'], 'verbose_name': 'منتج فرعي', 'verbose_name_plural': 'المنتجات الفرعية'},
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.item', verbose_name='المنتج الفرعي'),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(blank=True, help_text='المنتج اللي المنتج الفرعي ده تابع له. الوصفة (قماش/هالك/مصنعية) بتتعرّف على المنتج الرئيسي.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_products', to='inventory.product', verbose_name='المنتج الرئيسي'),
        ),
    ]
