# Generated by Django 5.1.15 on 2026-05-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_alter_item_options_alter_itemvariant_item_and_more'),
        ('manufacturing', '0031_productsizerecipe_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dozen_size',
            field=models.PositiveSmallIntegerField(default=12, help_text='الدستة = وحدة البيع الافتراضية. بتتطبّق على كل المنتجات الفرعية التابعة للمنتج ده.', verbose_name='عدد القطع في الدستة'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_type',
            field=models.ForeignKey(blank=True, help_text='نوع القماش/الخامة المستخدمة في تصنيع المنتج ده (من كتالوج «أنواع الأقمشة»).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='manufacturing.fabrictype', verbose_name='نوع القماش/الخامة'),
        ),
    ]
