# Generated by Django 5.1.15 on 2026-05-31 00:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_dozen_size_product_fabric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='waste_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='نسبة الزيادة على القماش بسبب الهالك — بتتحسب على المنتج كله مش لكل مقاس. مثال: 5 يعني الكمية المستخدمة بالهالك = الكمية قبل الهالك × 1.05.', max_digits=5, verbose_name='نسبة الهالك % (للمنتج كله)'),
        ),
    ]
