# Generated by Django 5.1.15 on 2026-05-31 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_waste_pct'),
        ('manufacturing', '0033_alter_productiongroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fabric_color',
            field=models.ForeignKey(blank=True, help_text='اللون اللي بيتخصم من مخزون القماش وقت الإنتاج. المخزون متخزّن باللون، فلازم تختار اللون عشان الخصم يبقى من نفس اللون الصح.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='manufacturing.fabriccolor', verbose_name='لون القماش المستخدم'),
        ),
    ]
