# Generated by Django 5.1.15 on 2026-06-12 00:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_fabric_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessory_waste_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='نسبة الزيادة على استهلاك الإكسسوارات بسبب الهالك في الإنتاج. مثال: 5 يعني الكمية المستهلكة = كمية الوصفة × 1.05.', max_digits=5, verbose_name='نسبة هالك الإكسسوارات % (للمنتج كله)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='waste_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='نسبة الزيادة على القماش بسبب الهالك — بتتحسب على المنتج كله مش لكل مقاس. مثال: 5 يعني الكمية المستخدمة بالهالك = الكمية قبل الهالك × 1.05.', max_digits=5, verbose_name='نسبة هالك القماش % (للمنتج كله)'),
        ),
    ]
