# Generated by Django 5.1.15 on 2026-06-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_journalline_accessory'),
        ('inventory', '0008_product_accessory_waste_pct_alter_product_waste_pct'),
        ('manufacturing', '0042_accessory_conversion_note_accessory_purchase_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoodsPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (FGP-0001 ...)', max_length=30, unique=True, verbose_name='رقم الفاتورة')),
                ('supplier_ref', models.CharField(blank=True, help_text='رقم الفاتورة الورقية اللي جايه من المورد (اختياري)', max_length=50, verbose_name='رقم فاتورة المورد')),
                ('date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('payment_method', models.CharField(choices=[('CASH', 'مدفوع (نقدية/بنك/محفظة)'), ('CREDIT', 'آجل (على المورد)')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّلة محاسبياً')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(blank=True, help_text='اختار الخزينة/البنك/المحفظة لو الدفع مش آجل', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_goods_invoices', to='core.cashaccount', verbose_name='مدفوع من (لو مدفوع)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('supplier', models.ForeignKey(blank=True, help_text='إجباري لو الفاتورة آجلة', limit_choices_to={'vendor_type__code': 'FINISHED_GOODS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_goods_invoices', to='manufacturing.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'فاتورة شراء منتجات تامة',
                'verbose_name_plural': 'مشتريات المنتجات التامة (تجارة)',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodsPurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّل')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.finishedgoodspurchaseinvoice', verbose_name='الفاتورة')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.itemvariant', verbose_name='المنتج (SKU)')),
            ],
            options={
                'verbose_name': 'بند منتج تام',
                'verbose_name_plural': 'بنود المنتجات التامة',
            },
        ),
    ]
