# Generated by Django 5.1.15 on 2026-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_seed_finished_goods_vendor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='carton_size',
            field=models.PositiveSmallIntegerField(default=0, help_text='كام قطعة في الكرتونة — لازم تتحدد لو هتبيع الصنف ده بالكرتونة في الفاتورة (سيبها صفر لو مش بتبيع بالكرتونة).', verbose_name='عدد القطع في الكرتونة'),
        ),
    ]
