# Generated by Django 5.1.15 on 2026-06-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_carton_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='carton_size',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MANUFACTURING', 'منتج تصنيع'), ('FINISHED', 'منتج تام')], default='MANUFACTURING', help_text='«تصنيع» = له وصفة وبيتصنّع بأوامر إنتاج. «تام» = بيتشترى جاهز ويتباع زي ما هو. لو اخترت «تام» هيتعمل منتج فرعي تلقائي بنفس الاسم تقدر تبيع منه.', max_length=15, verbose_name='نوع المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_unit',
            field=models.CharField(choices=[('DOZEN', 'دستة'), ('CARTON', 'كرتونة')], default='DOZEN', help_text='الوحدة اللي بتبيع بيها بالجملة — دستة ولا كرتونة. بتظهر في الفاتورة جنب «قطعة».', max_length=10, verbose_name='وحدة الجملة'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_unit_size',
            field=models.PositiveSmallIntegerField(default=12, help_text='كام قطعة في وحدة الجملة (الدستة أو الكرتونة).', verbose_name='عدد القطع في وحدة الجملة'),
        ),
    ]
