# Generated by Django 5.1.15 on 2026-06-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_item_carton_size_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodspurchaseline',
            name='purchase_unit',
            field=models.CharField(choices=[('PIECE', 'قطعة'), ('WHOLESALE', 'وحدة الجملة')], default='WHOLESALE', help_text='بتشتري بالقطعة ولا بوحدة الجملة (دستة/كرتونة). بيتخزّن في المخزون بالقطعة تلقائياً.', max_length=10, verbose_name='وحدة الشراء'),
        ),
        migrations.AlterField(
            model_name='finishedgoodspurchaseline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية (بالوحدة)'),
        ),
        migrations.AlterField(
            model_name='finishedgoodspurchaseline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, help_text='تكلفة القطعة أو الكرتونة/الدستة حسب وحدة الشراء.', max_digits=12, verbose_name='تكلفة الوحدة'),
        ),
    ]
