# Generated by Django 5.1.15 on 2026-06-20 00:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_finishedgoodspurchaseline_purchase_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='لما رصيد القطع ينزل عن العدد ده، يبقى وقت تطلب/تنتج تاني.', max_digits=12, verbose_name='حد إعادة الطلب (بالقطعة)'),
        ),
    ]
