# Generated by Django 5.1.15 on 2026-06-20 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_journalline_accessory'),
        ('inventory', '0014_alter_itemvariant_reorder_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (ST-0001 ...)', max_length=30, unique=True, verbose_name='رقم الجرد')),
                ('date', models.DateField(verbose_name='تاريخ الجرد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّل محاسبياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'جرد مخزون',
                'verbose_name_plural': 'جرد المخزون',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية الفعلية المعدودة')),
                ('system_qty_at_post', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='رصيد النظام وقت الترحيل')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّل')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake', verbose_name='الجرد')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='inventory.itemvariant', verbose_name='المنتج (SKU)')),
            ],
            options={
                'verbose_name': 'بند جرد',
                'verbose_name_plural': 'بنود الجرد',
            },
        ),
    ]
