# Generated by Django 5.1.15 on 2026-06-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stocktake_stocktakeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakeline',
            name='item',
            field=models.ForeignKey(blank=True, help_text='اختار المنتج الأول، وبعدين المقاس هيتفلتر عليه.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='stocktakeline',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='inventory.itemvariant', verbose_name='المقاس'),
        ),
    ]
