# Generated by Django 5.1.15 on 2026-06-26 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stocktakeline_item_alter_stocktakeline_variant'),
        ('manufacturing', '0046_fabricusage_fabric_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shorts_fabric_color',
            field=models.ForeignKey(blank=True, help_text='للأطقم بس: لون قماش الشورت اللي هيتخصم منه قماش الشورت وقت الإنتاج. سيبه فاضي لو المنتج مش طقم بلونين.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_shorts', to='manufacturing.fabriccolor', verbose_name='لون قماش الشورت'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fabric_color',
            field=models.ForeignKey(blank=True, help_text='اللون اللي بيتخصم من مخزون القماش وقت الإنتاج. المخزون متخزّن باللون، فلازم تختار اللون عشان الخصم يبقى من نفس اللون الصح. (للأطقم = لون الفانلة.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='manufacturing.fabriccolor', verbose_name='لون القماش المستخدم'),
        ),
    ]
