# Generated by Django 5.1.15 on 2026-05-25 12:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (FC-0001 ...)', max_length=20, unique=True, verbose_name='كود اللون')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم اللون')),
                ('is_raw', models.BooleanField(default=False, help_text='اختار ده للقماش لما يكون خام مش متصبّغ', verbose_name='خام (غير متصبّغ)')),
                ('hex_code', models.CharField(blank=True, help_text='مثال: #FF0000 — للعرض البصري في التقارير', max_length=7, verbose_name='كود HEX (اختياري)')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لون قماش',
                'verbose_name_plural': 'ألوان القماش',
                'ordering': ['-is_raw', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='FabricDyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (DYE-0001 ...)', max_length=20, unique=True, verbose_name='كود المصبغة')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المصبغة')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مصبغة',
                'verbose_name_plural': 'المصابغ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FabricSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (SUP-F-0001 ...)', max_length=20, unique=True, verbose_name='كود المورد')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='العنوان')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مورد قماش',
                'verbose_name_plural': 'موردي القماش',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (FT-0001 ...)', max_length=20, unique=True, verbose_name='كود النوع')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم النوع')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='وصف')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع قماش',
                'verbose_name_plural': 'أنواع القماش',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FabricBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (FB-0001 ...)', max_length=30, unique=True, verbose_name='رقم الدفعة')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('purchase_qty_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المشتراة (كيلو)')),
                ('purchase_unit_cost', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='سعر الكيلو من المورد')),
                ('purchase_payment_method', models.CharField(choices=[('CASH', 'كاش'), ('BANK', 'تحويل بنكي'), ('CREDIT', 'آجل (للمورد)')], default='CREDIT', max_length=10, verbose_name='طريقة السداد')),
                ('in_stock_qty_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الرصيد بالمخزن (كيلو)')),
                ('at_dyer_qty_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='في المصبغة (كيلو)')),
                ('total_dye_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي تكلفة التصبيغ')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّلة محاسبياً')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('color', models.ForeignKey(help_text='اللون اللي القماش عليه دلوقتي (خام لو لسه ما اتصبّغش)', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='manufacturing.fabriccolor', verbose_name='اللون الحالي')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='manufacturing.fabricsupplier', verbose_name='المورد')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='manufacturing.fabrictype', verbose_name='نوع القماش')),
            ],
            options={
                'verbose_name': 'دفعة قماش',
                'verbose_name_plural': 'دفعات القماش',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DyeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (DO-0001 ...)', max_length=30, unique=True, verbose_name='رقم أمر التصبيغ')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('sent_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='الوزن المُرسل (كيلو)')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('received_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='غالباً أقل من الوزن المرسل (فاقد التصبيغ)', max_digits=12, null=True, verbose_name='الوزن المُستلم (كيلو)')),
                ('dye_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='تكلفة التصبيغ')),
                ('dye_payment_method', models.CharField(choices=[('CASH', 'كاش'), ('BANK', 'تحويل بنكي'), ('CREDIT', 'آجل (للمصبغة)')], default='CREDIT', max_length=10, verbose_name='طريقة سداد التصبيغ')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SENT', 'في المصبغة'), ('RECEIVED', 'مستلم'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dye_orders', to='manufacturing.fabricbatch', verbose_name='دفعة القماش')),
                ('target_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='manufacturing.fabriccolor', verbose_name='اللون المطلوب')),
                ('dyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dye_orders', to='manufacturing.fabricdyer', verbose_name='المصبغة')),
            ],
            options={
                'verbose_name': 'أمر تصبيغ',
                'verbose_name_plural': 'أوامر التصبيغ',
                'ordering': ['-sent_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FabricMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'استلام من المورد'), ('SEND_TO_DYER', 'إرسال للمصبغة'), ('RECEIVE_FROM_DYER', 'استلام من المصبغة'), ('DYE_LOSS', 'فاقد التصبيغ'), ('ISSUE_TO_PRODUCTION', 'صرف للإنتاج'), ('ADJUST_IN', 'تسوية موجبة'), ('ADJUST_OUT', 'تسوية سالبة'), ('WASTE', 'إهدار / تالف')], max_length=30, verbose_name='نوع الحركة')),
                ('quantity_kg', models.DecimalField(decimal_places=3, help_text='كمية موجبة دائماً — نوع الحركة بيحدد in/out', max_digits=12, verbose_name='الكمية (كيلو)')),
                ('cost_per_kg_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='تكلفة الكيلو وقت الحركة')),
                ('document_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المستند')),
                ('document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المستند')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='manufacturing.fabricbatch', verbose_name='دفعة القماش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dye_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='manufacturing.dyeorder', verbose_name='أمر التصبيغ المرتبط')),
            ],
            options={
                'verbose_name': 'حركة قماش',
                'verbose_name_plural': 'حركات القماش',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['batch', 'date'], name='manufacturi_batch_i_594e71_idx'), models.Index(fields=['movement_type'], name='manufacturi_movemen_3c00da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fabricbatch',
            index=models.Index(fields=['supplier', 'purchase_date'], name='manufacturi_supplie_ebef71_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricbatch',
            index=models.Index(fields=['fabric_type', 'color'], name='manufacturi_fabric__e89fe4_idx'),
        ),
    ]
