# Generated by Django 5.1.15 on 2026-05-25 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_journalline_fabric_dyer_journalline_fabric_supplier'),
        ('manufacturing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (SP-0001 ...)', max_length=30, unique=True, verbose_name='رقم السند')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('method', models.CharField(choices=[('CASH', 'كاش'), ('BANK', 'تحويل بنكي'), ('CHEQUE', 'شيك')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع (رقم شيك / حوالة)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fabric_dyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='manufacturing.fabricdyer', verbose_name='المصبغة')),
                ('fabric_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='manufacturing.fabricsupplier', verbose_name='مورد القماش')),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'سند دفع لمورد',
                'verbose_name_plural': 'سندات دفع للموردين',
                'ordering': ['-date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('fabric_supplier__isnull', False), ('fabric_dyer__isnull', True)), models.Q(('fabric_supplier__isnull', True), ('fabric_dyer__isnull', False)), _connector='OR'), name='supplier_payment_one_party_only')],
            },
        ),
    ]
