# Generated by Django 5.1.15 on 2026-05-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_supplierpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (SUP-0001 ...)', max_length=20, unique=True, verbose_name='كود المورد')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='العنوان')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
                'ordering': ['vendor_type__sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود النوع')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='اسم النوع')),
                ('sort_order', models.PositiveSmallIntegerField(default=99, verbose_name='ترتيب العرض')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع مورد',
                'verbose_name_plural': 'أنواع الموردين',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.AlterModelOptions(
            name='fabricbatch',
            options={'ordering': ['-purchase_date', '-id'], 'verbose_name': 'شراء قماش', 'verbose_name_plural': 'مشتريات القماش'},
        ),
        migrations.RemoveConstraint(
            model_name='supplierpayment',
            name='supplier_payment_one_party_only',
        ),
        migrations.AlterField(
            model_name='dyeorder',
            name='dyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dye_orders', to='manufacturing.fabricdyer', verbose_name='المصبغة (legacy)'),
        ),
        migrations.AlterField(
            model_name='fabricbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='manufacturing.fabricsupplier', verbose_name='المورد (legacy)'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='fabric_dyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='manufacturing.fabricdyer', verbose_name='المصبغة (legacy)'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='fabric_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='manufacturing.fabricsupplier', verbose_name='مورد القماش (legacy)'),
        ),
        migrations.AddField(
            model_name='dyeorder',
            name='dyer_new',
            field=models.ForeignKey(blank=True, help_text='اختار مورد من نوع "مصبغة"', limit_choices_to={'vendor_type__code': 'DYER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dye_orders', to='manufacturing.supplier', verbose_name='المصبغة'),
        ),
        migrations.AddField(
            model_name='fabricbatch',
            name='supplier_new',
            field=models.ForeignKey(blank=True, help_text='اختار مورد من نوع "مورد قماش"', limit_choices_to={'vendor_type__code': 'FABRIC_SUPPLIER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabric_batches', to='manufacturing.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='اختار المورد اللي بتدفعله', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='manufacturing.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vendor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='manufacturing.vendortype', verbose_name='نوع المورد'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['vendor_type', 'active'], name='manufacturi_vendor__9466f6_idx'),
        ),
    ]
