# Generated by Django 5.1.15 on 2026-05-25 13:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_drop_legacy_vendor_fks'),
        ('manufacturing', '0006_delete_legacy_vendor_models'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (PO-0001 ...)', max_length=30, unique=True, verbose_name='رقم أمر الإنتاج')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('title', models.CharField(help_text='مثال: بيجاما أطفال صيفي 2026', max_length=200, verbose_name='اسم/وصف الموديل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('RELEASED', 'تم الإفراج (قيد التشغيل)'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=15, verbose_name='الحالة')),
                ('released_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الإفراج')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders', to=settings.AUTH_USER_MODEL)),
                ('completed_journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='لو الإنتاج لعميل معين بطلبية مخصصة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='sales.customer', verbose_name='العميل (اختياري)')),
                ('released_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_orders', to=settings.AUTH_USER_MODEL)),
                ('released_journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'أمر إنتاج',
                'verbose_name_plural': 'أوامر الإنتاج',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FabricUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المخصصة (كيلو)')),
                ('cost_per_kg_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=12, verbose_name='تكلفة الكيلو وقت الإفراج')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='manufacturing.fabricbatch', verbose_name='دفعة القماش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_usages', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'استهلاك قماش',
                'verbose_name_plural': 'استهلاكات القماش',
            },
        ),
        migrations.CreateModel(
            name='ProductionSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_model_no', models.PositiveSmallIntegerField(verbose_name='رقم الموديل الفرعي')),
                ('size', models.CharField(help_text='مثال: 5XS, 4XS, ..., 3XL أو 10, 12, 14, ...', max_length=10, verbose_name='المقاس')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية (عدد قطع)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'كمية مقاس',
                'verbose_name_plural': 'كميات المقاسات',
                'ordering': ['order', 'sub_model_no', 'size'],
                'unique_together': {('order', 'sub_model_no', 'size')},
            },
        ),
        migrations.CreateModel(
            name='ProductionSubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_model_no', models.PositiveSmallIntegerField(help_text='1, 2, 3, ... 6', verbose_name='رقم الموديل الفرعي')),
                ('fabric_description', models.CharField(blank=True, help_text='مثال: تريكو قطني خام، بوليستر، إلخ', max_length=200, verbose_name='نوع التريكو/اللياقة')),
                ('chest_type', models.CharField(choices=[('سادة', 'سادة'), ('طباعة', 'طباعة')], default='سادة', max_length=10, verbose_name='نوع الصدر')),
                ('chest_color', models.CharField(blank=True, max_length=100, verbose_name='لون الصدر')),
                ('chest_notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات الصدر')),
                ('back_type', models.CharField(choices=[('سادة', 'سادة'), ('طباعة', 'طباعة')], default='سادة', max_length=10, verbose_name='نوع الظهر')),
                ('back_color', models.CharField(blank=True, max_length=100, verbose_name='لون الظهر')),
                ('back_notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات الظهر')),
                ('sleeve_type', models.CharField(choices=[('سادة', 'سادة'), ('طباعة', 'طباعة')], default='سادة', max_length=10, verbose_name='نوع الكم')),
                ('sleeve_color', models.CharField(blank=True, max_length=100, verbose_name='لون الكم')),
                ('sleeve_notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات الكم')),
                ('shorts_pattern', models.CharField(blank=True, help_text='كابلس / فينو / إلخ', max_length=100, verbose_name='نوع الشورت')),
                ('shorts_type', models.CharField(choices=[('سادة', 'سادة'), ('طباعة', 'طباعة')], default='سادة', max_length=10, verbose_name='طباعة الشورت')),
                ('shorts_color', models.CharField(blank=True, max_length=100, verbose_name='لون الشورت')),
                ('shorts_notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات الشورت')),
                ('ticket', models.CharField(blank=True, max_length=50, verbose_name='التيكت')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='ملاحظات إضافية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_models', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'موديل فرعي',
                'verbose_name_plural': 'الموديلات الفرعية (بيانات القص)',
                'ordering': ['order', 'sub_model_no'],
                'unique_together': {('order', 'sub_model_no')},
            },
        ),
    ]
