# Generated by Django 5.1.15 on 2026-05-25 14:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_phase2b_planned_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (ACC-0001 ...)', max_length=20, unique=True, verbose_name='كود الإكسسوار')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الإكسسوار')),
                ('unit', models.CharField(default='قطعة', help_text='قطعة / متر / كيلو / لفة / إلخ', max_length=20, verbose_name='وحدة القياس')),
                ('default_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='يتعبا تلقائياً في AccessoryUsage', max_digits=12, verbose_name='سعر الوحدة الافتراضي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إكسسوار',
                'verbose_name_plural': 'الإكسسوارات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المرحلة')),
                ('sort_order', models.PositiveSmallIntegerField(default=99, verbose_name='الترتيب الافتراضي')),
                ('is_default', models.BooleanField(default=False, help_text='تتضاف تلقائياً لأي أمر إنتاج جديد', verbose_name='من المراحل الافتراضية')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مرحلة تشغيل (template)',
                'verbose_name_plural': 'قوالب مراحل التشغيل',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='title',
            field=models.CharField(help_text='مثال: بيجاما أطفال صيفي 2026. لو لسه ما اختارتش صنف فوق، الاسم ده هيبقى اسم الصنف الجديد.', max_length=200, verbose_name='اسم/وصف الموديل'),
        ),
        migrations.CreateModel(
            name='AccessoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المخطط')),
                ('actual_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الفعلي')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='يتعبا من الـ default للإكسسوار لو فاضي', max_digits=12, verbose_name='سعر الوحدة')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّل')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='manufacturing.accessory', verbose_name='الإكسسوار')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_usages', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
                ('supplier', models.ForeignKey(blank=True, help_text='لو محدد، التكلفة بتسجل عليه آجل بدلاً من كاش', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_usages', to='manufacturing.supplier', verbose_name='المورد (اختياري)')),
            ],
            options={
                'verbose_name': 'استهلاك إكسسوار',
                'verbose_name_plural': 'استهلاكات الإكسسوارات',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المرحلة')),
                ('sort_order', models.PositiveSmallIntegerField(help_text='غير الرقم لإعادة الترتيب (1, 2, 3, ...)', verbose_name='الترتيب')),
                ('qty_in', models.PositiveIntegerField(default=0, help_text='عدد القطع اللي دخلت المرحلة دي', verbose_name='كمية الدخول')),
                ('qty_out', models.PositiveIntegerField(default=0, help_text='عدد القطع اللي خرجت سليمة من المرحلة دي', verbose_name='كمية الخروج')),
                ('worker_name', models.CharField(blank=True, max_length=200, verbose_name='الصنايعي')),
                ('machine_name', models.CharField(blank=True, max_length=200, verbose_name='المكنة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'لم تبدأ'), ('IN_PROGRESS', 'قيد التشغيل'), ('DONE', 'مكتملة')], default='NOT_STARTED', max_length=15, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'مرحلة في أمر إنتاج',
                'verbose_name_plural': 'مراحل أوامر الإنتاج',
                'ordering': ['order', 'sort_order'],
            },
        ),
    ]
