# Generated by Django 5.1.15 on 2026-05-25 15:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_fabric_stage_setnull'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثال: S, M, L, XL, 2XL, 10, 12, 14', max_length=10, unique=True, verbose_name='المقاس')),
                ('sort_order', models.PositiveSmallIntegerField(default=99, help_text='للعرض في القوائم', verbose_name='الترتيب')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مقاس',
                'verbose_name_plural': 'المقاسات',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AlterModelOptions(
            name='productionsize',
            options={'ordering': ['order', 'sub_model__sub_model_no', 'size__sort_order'], 'verbose_name': 'كمية مقاس', 'verbose_name_plural': 'كميات المقاسات'},
        ),
        migrations.RemoveField(
            model_name='accessoryusage',
            name='planned_qty',
        ),
        migrations.AddField(
            model_name='fabriccolor',
            name='hsl',
            field=models.CharField(blank=True, help_text='مثال: 0,100%,50%', max_length=20, verbose_name='HSL'),
        ),
        migrations.AddField(
            model_name='fabriccolor',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='fabriccolor',
            name='rgb',
            field=models.CharField(blank=True, help_text='مثال: 255,0,0', max_length=20, verbose_name='RGB'),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='productionsize',
            name='sub_model',
            field=models.ForeignKey(default=1, help_text='اختار الموديل الفرعي من القائمة', on_delete=django.db.models.deletion.CASCADE, related_name='size_quantities', to='manufacturing.productionsubmodel', verbose_name='الموديل الفرعي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessoryusage',
            name='actual_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='اكتب الكمية لما الإنتاج يخلص — مفيش مخطط، بنحط الفعلي مباشرة', max_digits=12, verbose_name='الكمية الفعلية'),
        ),
        migrations.AlterField(
            model_name='fabriccolor',
            name='code',
            field=models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (CLR-001 ...)', max_length=20, unique=True, verbose_name='كود اللون'),
        ),
        migrations.AlterField(
            model_name='fabriccolor',
            name='hex_code',
            field=models.CharField(blank=True, help_text='مثال: #FF0000', max_length=7, verbose_name='كود HEX'),
        ),
        migrations.AlterField(
            model_name='fabriccolor',
            name='name_ar',
            field=models.CharField(help_text='يقبل عربي أو إنجليزي', max_length=100, verbose_name='اسم اللون'),
        ),
        migrations.AlterField(
            model_name='fabrictype',
            name='code',
            field=models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (FAB-001 ...)', max_length=20, unique=True, verbose_name='كود النوع'),
        ),
        migrations.AlterField(
            model_name='fabrictype',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='fabrictype',
            name='name_ar',
            field=models.CharField(help_text='يقبل عربي أو إنجليزي', max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterUniqueTogether(
            name='productionsize',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productionsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_sizes', to='manufacturing.size', verbose_name='المقاس'),
        ),
        migrations.AlterUniqueTogether(
            name='productionsize',
            unique_together={('sub_model', 'size')},
        ),
        migrations.RemoveField(
            model_name='productionsize',
            name='sub_model_no',
        ),
    ]
