# Generated by Django 5.1.15 on 2026-05-25 16:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0014_seed_sizes_fabrics_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricmovement',
            name='dye_order',
        ),
        migrations.AlterModelOptions(
            name='productionsubmodel',
            options={'ordering': ['order', 'sub_model_no'], 'verbose_name': 'ملاحظات منتج', 'verbose_name_plural': 'ملاحظات المنتج'},
        ),
        migrations.AlterUniqueTogether(
            name='productionsize',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='accessoryusage',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='accessoryusage',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='fabricbatch',
            name='at_dyer_qty_kg',
        ),
        migrations.RemoveField(
            model_name='fabricbatch',
            name='total_dye_cost',
        ),
        migrations.RemoveField(
            model_name='fabricusage',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='productionorderstage',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='productionorderstage',
            name='machine_name',
        ),
        migrations.AddField(
            model_name='accessory',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'vendor_type__code': 'ACCESSORIES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='manufacturing.supplier', verbose_name='المورد الافتراضي'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='default_unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='السعر الافتراضي للوحدة — يتاخد في الحسابات', max_digits=12, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='accessoryusage',
            name='actual_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='اكتب الكمية لما الإنتاج يخلص', max_digits=12, verbose_name='الكمية الفعلية'),
        ),
        migrations.AlterField(
            model_name='fabricmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE_IN', 'استلام من المورد'), ('ISSUE_TO_PRODUCTION', 'صرف للإنتاج'), ('ADJUST_IN', 'تسوية موجبة'), ('ADJUST_OUT', 'تسوية سالبة'), ('WASTE', 'إهدار / تالف')], max_length=30, verbose_name='نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='productionorderstage',
            name='qty_in',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='كمية الدخول (مجموع)'),
        ),
        migrations.AlterField(
            model_name='productionorderstage',
            name='qty_out',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='كمية الخروج (مجموع)'),
        ),
        migrations.AlterField(
            model_name='productionsize',
            name='sub_model',
            field=models.ForeignKey(blank=True, help_text='اختار اللي عايز تربطه به — أو سيبه فاضي لو مفيش تقسيم', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_quantities', to='manufacturing.productionsubmodel', verbose_name='ملاحظات المنتج (اختياري)'),
        ),
        migrations.CreateModel(
            name='StageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='مثال: مجموعة أحمد، مجموعة الصباحي', max_length=200, verbose_name='اسم المجموعة')),
                ('machine_name', models.CharField(blank=True, max_length=200, verbose_name='المكنة')),
                ('qty_in', models.PositiveIntegerField(default=0, verbose_name='الكمية الداخلة')),
                ('qty_out', models.PositiveIntegerField(default=0, verbose_name='الكمية الخارجة')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='ملاحظات')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='manufacturing.productionorderstage', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'مجموعة في مرحلة',
                'verbose_name_plural': 'مجموعات المراحل',
                'ordering': ['stage', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='DyeOrder',
        ),
    ]
