# Generated by Django 5.1.15 on 2026-05-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0016_size_single_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagegroup',
            options={'ordering': ['stage__sort_order', 'id'], 'verbose_name': 'مجموعة تشغيل', 'verbose_name_plural': 'مجموعات التشغيل'},
        ),
        migrations.AddField(
            model_name='stagegroup',
            name='order',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_groups', to='manufacturing.productionorder', verbose_name='أمر الإنتاج'),
        ),
    ]
