# Generated by Django 5.1.15 on 2026-05-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0017_alter_stagegroup_options_stagegroup_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingGroup',
            fields=[
            ],
            options={
                'verbose_name': 'مجموعة قص',
                'verbose_name_plural': 'أ) القص',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manufacturing.stagegroup',),
        ),
        migrations.CreateModel(
            name='IroningGroup',
            fields=[
            ],
            options={
                'verbose_name': 'مجموعة كوى',
                'verbose_name_plural': 'ج) الكوى والتكييس',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manufacturing.stagegroup',),
        ),
        migrations.CreateModel(
            name='SewingGroup',
            fields=[
            ],
            options={
                'verbose_name': 'مجموعة تشغيل',
                'verbose_name_plural': 'ب) مجموعات التشغيل',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manufacturing.stagegroup',),
        ),
    ]
