# Generated by Django 5.1.15 on 2026-05-28 14:11

from django.db import migrations


def fix_defaults(apps, schema_editor):
    """Default auto-seeded stages = تشغيل (1) + مكوى وتكييس (2). Cutting is now
    represented by the fabric-usage table, so it's no longer a default stage."""
    WorkStage = apps.get_model('manufacturing', 'WorkStage')
    WorkStage.objects.filter(name='قص').update(is_default=False)
    WorkStage.objects.update_or_create(
        name='تشغيل', defaults={'sort_order': 1, 'is_default': True, 'active': True})
    WorkStage.objects.update_or_create(
        name='مكوى وتكييس', defaults={'sort_order': 2, 'is_default': True, 'active': True})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0019_fix_default_stages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ironinggroup',
            options={'verbose_name': 'مجموعة كوى', 'verbose_name_plural': 'الكوى والتكييس'},
        ),
        migrations.AlterModelOptions(
            name='sewinggroup',
            options={'verbose_name': 'مجموعة تشغيل', 'verbose_name_plural': 'مجموعات التشغيل'},
        ),
        migrations.RunPython(fix_defaults, noop),
    ]
