# Generated by Django 5.1.15 on 2026-05-28 14:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0020_alter_ironinggroup_options_alter_sewinggroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryusage',
            name='actual_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='الكمية المستخدمة فعلياً — التكلفة بتتحسب منها مباشرة', max_digits=12, verbose_name='الكمية المستخدمة'),
        ),
        migrations.AlterField(
            model_name='stagegroup',
            name='qty_out',
            field=models.PositiveIntegerField(default=0, help_text='إجمالي خروج المراحل المفروض = إجمالي كميات المقاسات (دي اللي بتتنتج)', verbose_name='الكمية الخارجة'),
        ),
    ]
