# Generated by Django 5.1.15 on 2026-05-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0021_alter_accessoryusage_actual_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagegroup',
            name='qty_in',
        ),
        migrations.RemoveField(
            model_name='stagegroup',
            name='qty_out',
        ),
        migrations.AddField(
            model_name='stagegroup',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='عدد القطع اللي المجموعة دي أنتجتها. مجموع كل المجموعات المفروض = إجمالي كميات المقاسات.', verbose_name='كمية الإنتاج'),
        ),
    ]
