# Generated by Django 5.1.15 on 2026-05-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0022_remove_stagegroup_qty_in_remove_stagegroup_qty_out_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionsubmodel',
            options={'ordering': ['-id'], 'verbose_name': 'ملاحظات منتج', 'verbose_name_plural': 'ملاحظات المنتج'},
        ),
        migrations.AlterUniqueTogether(
            name='productionsubmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productionsize',
            name='sub_model',
            field=models.ForeignKey(blank=True, help_text='اضغط ➕ لإضافة ملاحظات/بيانات القص لهذا المقاس', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_quantities', to='manufacturing.productionsubmodel', verbose_name='ملاحظات المنتج'),
        ),
        migrations.AlterField(
            model_name='productionsubmodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_models', to='manufacturing.productionorder', verbose_name='أمر الإنتاج'),
        ),
        migrations.AlterField(
            model_name='productionsubmodel',
            name='sub_model_no',
            field=models.PositiveSmallIntegerField(blank=True, help_text='يتولد تلقائياً (1, 2, 3, ...)', null=True, verbose_name='رقم الموديل الفرعي'),
        ),
    ]
