# Generated by Django 5.1.15 on 2026-05-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0023_alter_productionsubmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorderstage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='stagegroup',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='stagegroup',
            name='order',
        ),
        migrations.DeleteModel(
            name='WorkStage',
        ),
        migrations.DeleteModel(
            name='CuttingGroup',
        ),
        migrations.DeleteModel(
            name='IroningGroup',
        ),
        migrations.DeleteModel(
            name='SewingGroup',
        ),
        migrations.DeleteModel(
            name='ProductionOrderStage',
        ),
        migrations.DeleteModel(
            name='StageGroup',
        ),
    ]
