# Generated by Django 5.1.15 on 2026-05-28 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0024_remove_productionorderstage_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='مثال: مجموعة أحمد، مجموعة الصباحي', max_length=200, verbose_name='اسم المجموعة')),
                ('machine_name', models.CharField(blank=True, max_length=200, verbose_name='المكنة')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='عدد القطع اللي المجموعة دي أنتجتها', verbose_name='كمية الإنتاج')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='ملاحظات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'مجموعة تشغيل',
                'verbose_name_plural': 'مجموعات التشغيل',
                'ordering': ['id'],
            },
        ),
    ]
