# Generated by Django 5.1.15 on 2026-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0025_productiongroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'خطة'), ('RELEASED', 'تم الإفراج (قديم)'), ('COMPLETED', 'تم الإنتاج'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=15, verbose_name='الحالة'),
        ),
    ]
