# Generated by Django 5.1.15 on 2026-05-30 12:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cashaccount_expensecategory_expensevoucher_and_more'),
        ('manufacturing', '0026_alter_productionorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='average_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=12, verbose_name='متوسط التكلفة'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14, verbose_name='الرصيد الحالي'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cash_account',
            field=models.ForeignKey(blank=True, help_text='الحساب اللى دفعت منه. سيبه فاضي عشان يستخدم الحساب الافتراضي.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='core.cashaccount', verbose_name='النقدية/البنك/المحفظة'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='default_unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='سعر استرشادي — التكلفة الفعلية بتيجي من متوسط تكلفة المشتريات', max_digits=12, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='unit',
            field=models.CharField(choices=[('قطعة', 'قطعة'), ('متر', 'متر'), ('كيلو', 'كيلو'), ('لفة', 'لفة'), ('طقم', 'طقم'), ('علبة', 'علبة'), ('دستة', 'دستة'), ('بكرة', 'بكرة')], default='قطعة', help_text='اختار وحدة القياس من القائمة', max_length=20, verbose_name='وحدة القياس'),
        ),
        migrations.CreateModel(
            name='AccessoryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (AP-0001 ...)', max_length=30, unique=True, verbose_name='رقم الشراء')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='سعر الوحدة')),
                ('payment_method', models.CharField(choices=[('CASH', 'مدفوع (نقدية/بنك/محفظة)'), ('CREDIT', 'آجل (على المورد)')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='manufacturing.accessory', verbose_name='الإكسسوار')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_purchases', to='core.cashaccount', verbose_name='مدفوع من (لو نقدي)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('supplier', models.ForeignKey(blank=True, help_text='إجباري لو الشراء آجل', limit_choices_to={'vendor_type__code': 'ACCESSORIES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_purchases', to='manufacturing.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'شراء إكسسوار',
                'verbose_name_plural': 'مشتريات الإكسسوارات',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
