# Generated by Django 5.1.15 on 2026-05-30 16:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_alter_item_options_alter_itemvariant_item_and_more'),
        ('manufacturing', '0027_accessory_average_cost_accessory_current_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_qty_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='كمية القماش اللي القطعة الواحدة من المقاس ده بتستهلكها — قبل إضافة الهالك.', max_digits=10, verbose_name='كمية القماش للقطعة (كيلو)')),
                ('waste_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='نسبة الزيادة على القماش بسبب الهالك. مثال: 5 يعني الكمية الفعلية = المخطط × 1.05.', max_digits=5, verbose_name='نسبة الهالك %')),
                ('labor_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='أجور التشغيل/المصنعية للقطعة الواحدة من المقاس ده. بتتضاف لتكلفة المخزون ومقابلها استحقاق في الميزانية.', max_digits=12, verbose_name='تكلفة المصنعية للقطعة')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_recipes', to='inventory.product', verbose_name='المنتج')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_recipes', to='manufacturing.size', verbose_name='المقاس')),
            ],
            options={
                'verbose_name': 'وصفة مقاس',
                'verbose_name_plural': 'وصفات المقاسات',
                'ordering': ['product', 'size__sort_order'],
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.CreateModel(
            name='ProductSizeAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_piece', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='كمية الإكسسوار اللي القطعة الواحدة بتستهلكها.', max_digits=12, verbose_name='الكمية للقطعة')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='manufacturing.accessory', verbose_name='الإكسسوار')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='manufacturing.productsizerecipe', verbose_name='وصفة المقاس')),
            ],
            options={
                'verbose_name': 'إكسسوار الوصفة',
                'verbose_name_plural': 'إكسسوارات الوصفة',
                'unique_together': {('recipe', 'accessory')},
            },
        ),
    ]
