# Generated by Django 5.1.15 on 2026-05-30 17:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_mfg_wage_accounts'),
        ('manufacturing', '0028_productsizerecipe_productsizeaccessory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingWagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (MW-0001 ...)', max_length=30, unique=True, verbose_name='رقم السند')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('payee', models.CharField(blank=True, help_text='اختياري — اسم اللي استلم المصنعية', max_length=200, verbose_name='المستفيد (اسم العامل/المشرف)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('CASH', 'كاش'), ('BANK', 'تحويل بنكي'), ('CHEQUE', 'شيك')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع (رقم شيك / حوالة)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('accrued_portion', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='المسدّد من المستحق')),
                ('expense_portion', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='الزيادة (فرق مصنعيات)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(blank=True, help_text='الحساب اللى دفعت منه. سيبه فاضي عشان يستخدم الحساب الافتراضي.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wage_payments', to='core.cashaccount', verbose_name='النقدية/البنك/المحفظة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'صرف مصنعيات',
                'verbose_name_plural': 'صرف المصنعيات',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
