# Generated by Django 5.1.15 on 2026-05-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_alter_item_options_alter_itemvariant_item_and_more'),
        ('manufacturing', '0029_manufacturingwagepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='item',
            field=models.ForeignKey(blank=True, help_text='اختار منتج فرعي موجود لو الموديل ده اتعمل قبل كده. سيب الخانة فاضية لو موديل جديد — هيتعمل تلقائياً باسم/كود الموديل الجديد.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.item', verbose_name='الموديل (منتج فرعي)'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='title',
            field=models.CharField(help_text='مثال: بيجاما أطفال صيفي 2026. لو لسه ما اختارتش منتج فرعي فوق، الاسم ده هيبقى اسم المنتج الفرعي الجديد.', max_length=200, verbose_name='اسم/وصف الموديل'),
        ),
    ]
