# Generated by Django 5.1.15 on 2026-05-30 17:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0030_relabel_productionorder_item_subproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizerecipe',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='سعر بيع القطعة الواحدة من المقاس ده. بيتطبّق على كل المنتجات الفرعية التابعة للمنتج الرئيسي. سعر الدستة = ده × عدد القطع في الدستة.', max_digits=12, verbose_name='سعر البيع للقطعة'),
        ),
    ]
