# Generated by Django 5.1.15 on 2026-05-31 00:08
#
# Hand-edited after autogeneration so the data is preserved:
#   1) Add the new fields (fabric_type on FabricUsage, the 4-stage columns on
#      ProductionGroup, reorder_level on ProductSizeRecipe) + relabel/alter.
#   2) RunPython: copy the OLD single-stage ProductionGroup data into the new
#      "sewing" stage, and seed Product.waste_pct from the (soon-to-be-removed)
#      per-size recipe waste — while BOTH old and new columns still exist.
#   3) Only then remove the old columns.

import django.db.models.deletion
from collections import defaultdict
from decimal import Decimal
from django.db import migrations, models


def forward(apps, schema_editor):
    """Preserve data before the old columns get dropped."""
    # 1) ProductionGroup: old (group_name / machine_name / quantity) -> sewing stage.
    ProductionGroup = apps.get_model('manufacturing', 'ProductionGroup')
    for g in ProductionGroup.objects.all():
        old_group = (getattr(g, 'group_name', '') or '').strip()
        old_machine = (getattr(g, 'machine_name', '') or '').strip()
        old_qty = getattr(g, 'quantity', 0) or 0
        changed = False
        if old_group and not g.sewing_group:
            g.sewing_group = old_group[:200]
            changed = True
        if old_qty and not g.sewing_qty:
            g.sewing_qty = old_qty
            changed = True
        if old_machine:
            note = (g.notes or '').strip()
            tag = f'مكنة: {old_machine}'
            if tag not in note:
                g.notes = (f'{note} | {tag}' if note else tag)[:300]
                changed = True
        if changed:
            g.save()

    # 2) Seed Product.waste_pct from the MAX per-size recipe waste (kept lossless;
    #    in this DB all recipe waste = 0, so every product stays at its default 0).
    ProductSizeRecipe = apps.get_model('manufacturing', 'ProductSizeRecipe')
    Product = apps.get_model('inventory', 'Product')
    maxw = defaultdict(lambda: Decimal('0'))
    for r in ProductSizeRecipe.objects.all():
        w = r.waste_pct or Decimal('0')
        if w > maxw[r.product_id]:
            maxw[r.product_id] = w
    for pid, w in maxw.items():
        if w and w > 0:
            Product.objects.filter(pk=pid).update(waste_pct=w)


def backward(apps, schema_editor):
    """Best-effort reverse: copy the sewing stage back to the old single columns."""
    ProductionGroup = apps.get_model('manufacturing', 'ProductionGroup')
    for g in ProductionGroup.objects.all():
        if hasattr(g, 'group_name'):
            g.group_name = (g.sewing_group or '')[:200]
            g.quantity = g.sewing_qty or 0
            g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0032_backfill_recipe_selling_price'),
        ('inventory', '0006_product_waste_pct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productiongroup',
            options={'ordering': ['id'], 'verbose_name': 'مرحلة تشغيل', 'verbose_name_plural': 'مجموعات ومراحل التشغيل'},
        ),
        # --- 1) add new fields + relabel existing ones (old columns still present) ---
        migrations.AddField(
            model_name='fabricusage',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='manufacturing.fabrictype', verbose_name='نوع القماش/الخامة'),
        ),
        migrations.AddField(
            model_name='productiongroup',
            name='sewing_group',
            field=models.CharField(blank=True, help_text='اسم مجموعة/ورشة التشغيل (الخياطة)', max_length=200, verbose_name='مجموعة التشغيل'),
        ),
        migrations.AddField(
            model_name='productiongroup',
            name='sewing_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='كمية التشغيل'),
        ),
        migrations.AddField(
            model_name='productiongroup',
            name='finishing_group',
            field=models.CharField(blank=True, max_length=200, verbose_name='مجموعة التشطيب'),
        ),
        migrations.AddField(
            model_name='productiongroup',
            name='finishing_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='كمية التشطيب'),
        ),
        migrations.AddField(
            model_name='productiongroup',
            name='quality_group',
            field=models.CharField(blank=True, max_length=200, verbose_name='مجموعة الجودة'),
        ),
        migrations.AddField(
            model_name='productiongroup',
            name='quality_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='كمية الجودة'),
        ),
        migrations.AddField(
            model_name='productiongroup',
            name='ironing_group',
            field=models.CharField(blank=True, max_length=200, verbose_name='مجموعة الكوي'),
        ),
        migrations.AddField(
            model_name='productiongroup',
            name='ironing_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='كمية الكوي'),
        ),
        migrations.AddField(
            model_name='productsizerecipe',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='لما رصيد المقاس ده ينزل عن العدد ده من الدستات، يبقى وقت تطلب/تنتج تاني. بيتطبّق على كل المنتجات الفرعية التابعة للمنتج الرئيسي.', max_digits=12, verbose_name='حد إعادة الطلب (بالدستة)'),
        ),
        migrations.AlterField(
            model_name='fabricusage',
            name='actual_qty_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='الكمية قبل الهالك + الهالك (اللي اتخصمت فعلياً)', max_digits=12, verbose_name='الكمية المستخدمة بالهالك (كيلو)'),
        ),
        migrations.AlterField(
            model_name='fabricusage',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='manufacturing.fabricbatch', verbose_name='دفعة القماش (اتخصم منها)'),
        ),
        migrations.AlterField(
            model_name='fabricusage',
            name='cost_per_kg_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=12, verbose_name='تكلفة الكيلو (متوسط وقت الإنتاج)'),
        ),
        migrations.AlterField(
            model_name='fabricusage',
            name='planned_qty_kg',
            field=models.DecimalField(decimal_places=3, help_text='الكمية من الوصفة قبل إضافة الهالك', max_digits=12, verbose_name='الكمية قبل الهالك (كيلو)'),
        ),
        # --- 2) preserve data while both old + new columns exist ---
        migrations.RunPython(forward, backward),
        # --- 3) now drop the old columns ---
        migrations.RemoveField(
            model_name='productiongroup',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='productiongroup',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='productiongroup',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productsizerecipe',
            name='waste_pct',
        ),
    ]
