# Generated by Django 5.1.15 on 2026-05-31 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_fabric_color'),
        ('manufacturing', '0033_alter_productiongroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='item',
            field=models.ForeignKey(blank=True, help_text='اختار المنتج الفرعي بتاع الأمر. الخامة (نوع القماش) بتيجي من المنتج الرئيسي، ولون القماش اللي هيتخصم من المخزن بييجي من المنتج الفرعي ده.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.item', verbose_name='الموديل (منتج فرعي)'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='title',
            field=models.CharField(blank=True, help_text='بيتعبّى تلقائياً باسم المنتج الفرعي.', max_length=200, verbose_name='اسم/وصف الموديل'),
        ),
    ]
