# Generated by Django 5.1.15 on 2026-05-31 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fixedasset_supplier_invoice_no'),
        ('manufacturing', '0034_alter_productionorder_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (API-0001 ...)', max_length=30, unique=True, verbose_name='رقم الفاتورة')),
                ('supplier_ref', models.CharField(blank=True, help_text='رقم الفاتورة الورقية اللي جايه من المورد (اختياري)', max_length=50, verbose_name='رقم فاتورة المورد')),
                ('date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('payment_method', models.CharField(choices=[('CASH', 'مدفوع (نقدية/بنك/محفظة)'), ('CREDIT', 'آجل (على المورد)')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّلة محاسبياً')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(blank=True, help_text='اختار الخزينة/البنك/المحفظة لو الدفع مش آجل', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_invoices', to='core.cashaccount', verbose_name='مدفوع من (لو مدفوع)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('supplier', models.ForeignKey(blank=True, help_text='إجباري لو الفاتورة آجلة', limit_choices_to={'vendor_type__code': 'ACCESSORIES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_invoices', to='manufacturing.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'فاتورة شراء إكسسوارات',
                'verbose_name_plural': 'فواتير شراء الإكسسوارات',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='accessorypurchase',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='يتساب فاضي للشراء المفرد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.accessorypurchaseinvoice', verbose_name='فاتورة الشراء'),
        ),
        migrations.CreateModel(
            name='FabricPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (FPI-0001 ...)', max_length=30, unique=True, verbose_name='رقم الفاتورة')),
                ('supplier_ref', models.CharField(blank=True, help_text='رقم الفاتورة الورقية اللي جايه من المورد (اختياري)', max_length=50, verbose_name='رقم فاتورة المورد')),
                ('date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('payment_method', models.CharField(choices=[('CASH', 'كاش'), ('BANK', 'تحويل بنكي'), ('CREDIT', 'آجل (للمورد)')], default='CREDIT', max_length=10, verbose_name='طريقة السداد')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّلة محاسبياً')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(blank=True, help_text='اختار الخزينة/البنك/المحفظة لو السداد مش آجل', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabric_invoices', to='core.cashaccount', verbose_name='مدفوع من (لو كاش/بنك)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('supplier', models.ForeignKey(help_text='اختار مورد من نوع "مورد قماش"', limit_choices_to={'vendor_type__code': 'FABRIC_SUPPLIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='fabric_invoices', to='manufacturing.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'فاتورة شراء قماش',
                'verbose_name_plural': 'فواتير شراء القماش',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='fabricbatch',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='يتساب فاضي للشراء المفرد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.fabricpurchaseinvoice', verbose_name='فاتورة الشراء'),
        ),
    ]
