# Generated by Django 5.1.15 on 2026-06-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fixedasset_supplier_invoice_no'),
        ('manufacturing', '0035_accessorypurchaseinvoice_accessorypurchase_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingwagepayment',
            name='expense_category',
            field=models.ForeignKey(blank=True, help_text='بند المصروف لتصنيف الصرف وتجميعه في القوائم والتقارير (للتصنيف فقط — مش بيغيّر القيد المحاسبي؛ الصرف بيترحّل زي ما هو).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.expensecategory', verbose_name='نوع المصروف'),
        ),
    ]
