# Generated by Django 5.1.15 on 2026-06-11 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0036_manufacturingwagepayment_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionIroningRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(blank=True, max_length=200, verbose_name='الصنايعي')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ironing_rows', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'صف كوي',
                'verbose_name_plural': 'مرحلة الكوي',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOperationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(blank=True, max_length=200, verbose_name='الصنايعي')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('stage_no', models.CharField(blank=True, max_length=30, verbose_name='رقم المرحلة')),
                ('stage_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المرحلة')),
                ('machine', models.CharField(blank=True, max_length=200, verbose_name='المكنة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_rows', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'صف تشغيل',
                'verbose_name_plural': 'مراحل التشغيل',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionPrintingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(blank=True, max_length=200, verbose_name='الصنايعي')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_rows', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'صف طباعة',
                'verbose_name_plural': 'مرحلة الطباعة',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionQualityRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(blank=True, max_length=200, verbose_name='الصنايعي')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_rows', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'صف جودة',
                'verbose_name_plural': 'مرحلة الجودة',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductionGroup',
        ),
    ]
