# Generated by Django 5.1.15 on 2026-06-12 00:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0037_productionironingrow_productionoperationrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='waste_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='نسبة الزيادة على استهلاك الإكسسوار بسبب الهالك. مثال: 5 يعني الكمية المستهلكة = كمية الوصفة × 1.05.', max_digits=5, verbose_name='نسبة الهالك %'),
        ),
    ]
