# Generated by Django 5.1.15 on 2026-06-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0039_seed_tatbiq_paper_and_waste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='waste_pct',
        ),
    ]
