# Generated by Django 5.1.15 on 2026-06-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0040_remove_accessory_waste_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='اختار مورد من نوع "مورد قماش" (اختياري للأرصدة الافتتاحية)', limit_choices_to={'vendor_type__code': 'FABRIC_SUPPLIER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabric_batches', to='manufacturing.supplier', verbose_name='المورد'),
        ),
    ]
