# Generated by Django 5.1.15 on 2026-06-12 14:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0041_alter_fabricbatch_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='conversion_note',
            field=models.CharField(blank=True, help_text='توضيح اختياري، مثال: «وزن المتر 100 جرام»', max_length=200, verbose_name='شرح المعدل'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='purchase_unit',
            field=models.CharField(choices=[('قطعة', 'قطعة'), ('متر', 'متر'), ('كيلو', 'كيلو'), ('لفة', 'لفة'), ('طقم', 'طقم'), ('علبة', 'علبة'), ('دستة', 'دستة'), ('بكرة', 'بكرة')], default='قطعة', help_text='الوحدة اللي بتشتري بيها من المورد', max_length=20, verbose_name='وحدة الشراء'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='units_per_purchase',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='كام وحدة استهلاك في وحدة الشراء الواحدة. مثال: بتشتري بالكيلو وتستهلك بالمتر والمتر وزنه 100 جرام → 1000÷100 = 10 متر في الكيلو. لو الوحدتين نفس الوحدة سيبها 1.', max_digits=12, verbose_name='المعدل (وحدات استهلاك لكل وحدة شراء)'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='unit',
            field=models.CharField(choices=[('قطعة', 'قطعة'), ('متر', 'متر'), ('كيلو', 'كيلو'), ('لفة', 'لفة'), ('طقم', 'طقم'), ('علبة', 'علبة'), ('دستة', 'دستة'), ('بكرة', 'بكرة')], default='قطعة', help_text='الوحدة اللي بتستهلك بيها في الإنتاج (المخزون والتكلفة محسوبين بيها)', max_length=20, verbose_name='وحدة الاستهلاك'),
        ),
        migrations.AlterField(
            model_name='accessorypurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='الكمية بوحدة الشراء — النظام يحوّلها لوحدة الاستهلاك تلقائياً', max_digits=14, verbose_name='الكمية (بوحدة الشراء)'),
        ),
        migrations.AlterField(
            model_name='accessorypurchase',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='سعر وحدة الشراء'),
        ),
    ]
