# Generated by Django 5.1.15 on 2026-06-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0042_accessory_conversion_note_accessory_purchase_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricpurchaseinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='إجباري لو الفاتورة آجلة. سيبه فاضي لو كاش/بنك.', limit_choices_to={'vendor_type__code': 'FABRIC_SUPPLIER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabric_invoices', to='manufacturing.supplier', verbose_name='المورد'),
        ),
    ]
