# Generated by Django 5.1.15 on 2026-06-20 00:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0043_alter_fabricpurchaseinvoice_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizerecipe',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='لما رصيد القطع للمقاس ده ينزل عن العدد ده، يبقى وقت تطلب/تنتج تاني. بيتطبّق على كل المنتجات الفرعية التابعة للمنتج الرئيسي.', max_digits=12, verbose_name='حد إعادة الطلب (بالقطعة)'),
        ),
    ]
