# Generated by Django 5.1.15 on 2026-06-20 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_journalline_accessory'),
        ('manufacturing', '0044_alter_productsizerecipe_reorder_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingWageAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (MWA-0001 ...)', max_length=30, unique=True, verbose_name='رقم التسوية')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('direction', models.CharField(choices=[('INCREASE', 'زيادة المصنعيات (تكلفة أكبر)'), ('DECREASE', 'نقص المصنعيات (تكلفة أقل)')], default='INCREASE', max_length=10, verbose_name='نوع التسوية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='السبب / ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'تسوية مصنعيات',
                'verbose_name_plural': 'تسويات المصنعيات (آخر السنة)',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
