# Generated by Django 5.1.15 on 2026-06-26 12:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0045_manufacturingwageadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricusage',
            name='fabric_color',
            field=models.ForeignKey(blank=True, help_text='لون القماش اللي اتخصم منه — بيتسجّل على الصف المخطط والفعلي عشان نفرّق الفانلة عن الشورت.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='manufacturing.fabriccolor', verbose_name='لون القماش'),
        ),
        migrations.AddField(
            model_name='productsizerecipe',
            name='shorts_fabric_qty_kg',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='للأطقم بس: كمية قماش الشورت للقطعة الواحدة (قبل الهالك). بتتخصم من لون الشورت بتاع المنتج الفرعي. سيبها 0 لو المنتج مش طقم بلونين.', max_digits=10, verbose_name='قماش الشورت للقطعة (كيلو)'),
        ),
        migrations.AlterField(
            model_name='productsizerecipe',
            name='fabric_qty_kg',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='كمية القماش اللي القطعة الواحدة من المقاس ده بتستهلكها — قبل إضافة الهالك. (للأطقم = قماش الفانلة.)', max_digits=10, verbose_name='كمية القماش للقطعة (كيلو)'),
        ),
    ]
