# Generated by Django 5.1.15 on 2026-06-27 15:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0046_fabricusage_fabric_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='opening_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=12, verbose_name='تكلفة الوحدة الافتتاحية'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='opening_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, help_text='الكمية اللي اترفع بيها أول مرة في الأرصدة الافتتاحية (ثابتة — مش بتتغير بالاستهلاك).', max_digits=14, verbose_name='الرصيد الافتتاحي'),
        ),
    ]
