# Generated by Django 5.1.15 on 2026-07-11 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_journalline_accessory'),
        ('manufacturing', '0047_accessory_opening_cost_accessory_opening_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryStockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (AST-0001 ...)', max_length=30, unique=True, verbose_name='رقم الجرد')),
                ('date', models.DateField(verbose_name='تاريخ الجرد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّل محاسبياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'جرد إكسسوارات',
                'verbose_name_plural': 'جرد الإكسسوارات',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccessoryStockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='الكمية الفعلية المعدودة (وحدة الاستهلاك)')),
                ('system_qty_at_post', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=14, null=True, verbose_name='رصيد النظام وقت الترحيل')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّل')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='manufacturing.accessory', verbose_name='الإكسسوار')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.accessorystocktake', verbose_name='الجرد')),
            ],
            options={
                'verbose_name': 'بند جرد إكسسوار',
                'verbose_name_plural': 'بنود جرد الإكسسوارات',
            },
        ),
        migrations.CreateModel(
            name='FabricStockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (FST-0001 ...)', max_length=30, unique=True, verbose_name='رقم الجرد')),
                ('date', models.DateField(verbose_name='تاريخ الجرد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّل محاسبياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'جرد قماش',
                'verbose_name_plural': 'جرد القماش',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FabricStockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية الفعلية المعدودة (كيلو)')),
                ('system_qty_at_post', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=12, null=True, verbose_name='رصيد النظام وقت الترحيل')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='مرحّل')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='manufacturing.fabriccolor', verbose_name='اللون')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='manufacturing.fabrictype', verbose_name='نوع القماش')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.fabricstocktake', verbose_name='الجرد')),
            ],
            options={
                'verbose_name': 'بند جرد قماش',
                'verbose_name_plural': 'بنود جرد القماش',
            },
        ),
    ]
