# Generated by Django 5.1.15 on 2026-07-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0048_accessorystocktake_accessorystocktakeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorystocktakeline',
            name='counted_qty',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='الكمية الفعلية المعدودة (بوحدة الشراء)'),
        ),
        migrations.AlterField(
            model_name='accessorystocktakeline',
            name='system_qty_at_post',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=14, null=True, verbose_name='رصيد النظام وقت الترحيل (بوحدة الشراء)'),
        ),
    ]
