# Generated by Django 5.1.15 on 2026-07-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0049_alter_accessorystocktakeline_counted_qty_and_more'),
        ('sales', '0006_alter_salesinvoiceline_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, editable=False, help_text='بتتسجّل لما الأمر يتحوّل لبنود فاتورة بيع.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='sales.salesinvoice', verbose_name='فاتورة البيع'),
        ),
    ]
