# Generated by Django 5.1.15 on 2026-07-18 08:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0050_productionorder_sales_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrictype',
            name='unit',
            field=models.CharField(choices=[('كيلو', 'كيلو'), ('متر', 'متر')], default='كيلو', help_text='الوحدة اللي بتشتري وتستهلك بيها القماش ده. الأقمشة العادية بالكيلو، وقماش زي «ايزيس» بالمتر.', max_length=10, verbose_name='وحدة القياس'),
        ),
        migrations.CreateModel(
            name='ProductSizeFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_piece', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='كمية القماش للقطعة الواحدة بوحدة النوع (كيلو/متر).', max_digits=12, verbose_name='الكمية للقطعة')),
                ('fabric_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.fabriccolor', verbose_name='اللون')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.fabrictype', verbose_name='نوع القماش')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='manufacturing.productsizerecipe', verbose_name='وصفة المقاس')),
            ],
            options={
                'verbose_name': 'قماش الوصفة',
                'verbose_name_plural': 'أقمشة الوصفة',
                'unique_together': {('recipe', 'fabric_type', 'fabric_color')},
            },
        ),
    ]
