# Generated by Django 5.1.15 on 2026-07-18 08:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0051_fabrictype_unit_productsizefabric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricbatch',
            name='in_stock_qty_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الرصيد بالمخزن (كيلو/متر حسب النوع)'),
        ),
        migrations.AlterField(
            model_name='fabricbatch',
            name='purchase_qty_kg',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المشتراة (كيلو/متر حسب النوع)'),
        ),
        migrations.AlterField(
            model_name='fabricbatch',
            name='purchase_unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='سعر الوحدة من المورد (كيلو/متر)'),
        ),
    ]
