# Generated by Django 5.1.15 on 2026-07-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0052_alter_fabricbatch_in_stock_qty_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UninvoicedProductionOrder',
            fields=[
            ],
            options={
                'verbose_name': 'أمر لم يتم بيعه',
                'verbose_name_plural': 'أوامر لم يتم بيعها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manufacturing.productionorder',),
        ),
    ]
