# Generated by Django 5.1.15 on 2026-05-25 11:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (C0001, C0002 ...)', max_length=20, unique=True, verbose_name='كود العميل')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (English)')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='العنوان')),
                ('governorate', models.CharField(blank=True, choices=[('الإسكندرية', 'الإسكندرية'), ('الإسماعيلية', 'الإسماعيلية'), ('الأقصر', 'الأقصر'), ('البحر الأحمر', 'البحر الأحمر'), ('البحيرة', 'البحيرة'), ('الجيزة', 'الجيزة'), ('الدقهلية', 'الدقهلية'), ('السويس', 'السويس'), ('الشرقية', 'الشرقية'), ('الغربية', 'الغربية'), ('الفيوم', 'الفيوم'), ('القاهرة', 'القاهرة'), ('القليوبية', 'القليوبية'), ('المنوفية', 'المنوفية'), ('المنيا', 'المنيا'), ('الوادي الجديد', 'الوادي الجديد'), ('أسوان', 'أسوان'), ('أسيوط', 'أسيوط'), ('بني سويف', 'بني سويف'), ('بورسعيد', 'بورسعيد'), ('جنوب سيناء', 'جنوب سيناء'), ('دمياط', 'دمياط'), ('سوهاج', 'سوهاج'), ('شمال سيناء', 'شمال سيناء'), ('قنا', 'قنا'), ('كفر الشيخ', 'كفر الشيخ'), ('مطروح', 'مطروح')], max_length=100, verbose_name='المحافظة')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('payment_terms_days', models.PositiveIntegerField(default=0, verbose_name='شروط السداد (أيام)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='حد الائتمان')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الرصيد الافتتاحي')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (REC-0001, REC-0002 ...)', max_length=30, unique=True, verbose_name='رقم السند')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK', 'تحويل بنكي'), ('CHEQUE', 'شيك'), ('POS', 'نقاط بيع')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='sales.customer', verbose_name='العميل')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'سند قبض',
                'verbose_name_plural': 'سندات القبض',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (INV-0001, INV-0002 ...)', max_length=30, unique=True, verbose_name='رقم الفاتورة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي قبل الخصم')),
                ('doc_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='إذا أدخلت نسبة، يتم حساب القيمة تلقائياً.', max_digits=5, verbose_name='نسبة خصم التاجر %')),
                ('doc_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='خصم التاجر')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي')),
                ('cash_payment_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='النسبة المتفق على دفعها كاش عند الاستلام', max_digits=5, verbose_name='نسبة الدفعة الكاش %')),
                ('installment_frequency', models.CharField(blank=True, choices=[('', 'بدون'), ('WEEKLY', 'أسبوعي'), ('MONTHLY', 'شهري')], default='', help_text='كيف يتم دفع باقي المبلغ', max_length=10, verbose_name='نظام السداد')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّلة'), ('CANCELLED', 'ملغاة')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.customer', verbose_name='العميل')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فاتورة مبيعات',
                'verbose_name_plural': 'فواتير المبيعات',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المخصص')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.receipt')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.salesinvoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'تخصيص دفعة',
                'verbose_name_plural': 'تخصيصات الدفعات',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='عدد المجموعات لو "ثري" — عدد القطع لو بيع بالقطعة', max_digits=12, verbose_name='العدد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي')),
                ('cogs_at_posting', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تكلفة البضاعة المباعة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف')),
                ('variant', models.ForeignKey(blank=True, help_text='سيب الخانة دي على "ثري" للبيع بالمجموعة (4 مقاسات). اختار مقاس محدد للبيع بالقطعة.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.itemvariant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفواتير',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(blank=True, help_text='سيب الخانة فاضية وهيتولّد تلقائياً (RET-0001, RET-0002 ...)', max_length=30, unique=True, verbose_name='رقم المرتجع')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('reason', models.CharField(blank=True, help_text='مثلاً: عيب مصنعى — مقاس غلط — تبديل', max_length=200, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي قيمة المرتجع')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المبلغ المخصوم من المستحق')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.customer', verbose_name='العميل')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.salesinvoice', verbose_name='الفاتورة الأصلية (اختياري)')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مرتجع مبيعات',
                'verbose_name_plural': 'مرتجعات المبيعات',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='العدد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة المُسترد')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي')),
                ('cogs_at_posting', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تكلفة البضاعة المرتجعة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف')),
                ('return_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesreturn')),
                ('variant', models.ForeignKey(blank=True, help_text='سيب الخانة على "ثري" لمرتجع مجموعة كاملة — اختار مقاس لمرتجع قطعة واحدة', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.itemvariant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'بند مرتجع',
                'verbose_name_plural': 'بنود المرتجعات',
            },
        ),
    ]
