# Generated by Django 5.1.15 on 2026-05-28 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_dozen_size_itemvariant_selling_price_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='item',
            field=models.ForeignKey(blank=True, help_text='بيتحدد تلقائياً من المقاس المختار', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='ممكن تكتب 0.5 لنص دستة، 1 لدستة، 2 لدستتين...', max_digits=12, verbose_name='عدد الدستات'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='يتعبا تلقائياً = سعر بيع القطعة × عدد القطع في الدستة', max_digits=12, verbose_name='سعر الدستة'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='اختار المقاس اللي بتبيعه', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.itemvariant', verbose_name='المقاس'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='item',
            field=models.ForeignKey(blank=True, help_text='بيتحدد تلقائياً من المقاس', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='ممكن 0.5 لنص دستة', max_digits=12, verbose_name='عدد الدستات'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الدستة المُسترد'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='اختار المقاس المرتجع', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.itemvariant', verbose_name='المقاس'),
        ),
    ]
