# Generated by Django 5.1.15 on 2026-05-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cashaccount_expensecategory_expensevoucher_and_more'),
        ('sales', '0002_alter_salesinvoiceline_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cash_account',
            field=models.ForeignKey(blank=True, help_text='الحساب اللى استلمت فيه الفلوس. سيبه فاضي عشان يستخدم الحساب الافتراضي.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.cashaccount', verbose_name='النقدية/البنك/المحفظة'),
        ),
    ]
