# Generated by Django 5.1.15 on 2026-06-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_receipt_cash_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='عدد القطع المباعة من المقاس ده.', max_digits=12, verbose_name='عدد القطع'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='يتعبا تلقائياً = سعر بيع القطعة من الوصفة', max_digits=12, verbose_name='سعر القطعة'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='عدد القطع المرتجعة من المقاس ده.', max_digits=12, verbose_name='عدد القطع'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر القطعة المُسترد'),
        ),
    ]
