# Generated by Django 5.1.15 on 2026-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesinvoiceline_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='sale_unit',
            field=models.CharField(choices=[('PIECE', 'قطعة'), ('DOZEN', 'دستة'), ('CARTON', 'كرتونة')], default='PIECE', help_text='تبيع بالقطعة ولا الدستة ولا الكرتونة. الكمية والسعر بيتحسبوا على حسب الوحدة.', max_length=10, verbose_name='وحدة البيع'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='العدد بوحدة البيع المختارة (قطع/دستات/كراتين).', max_digits=12, verbose_name='العدد (بالوحدة)'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='يتعبا تلقائياً = سعر القطعة × عدد القطع في الوحدة', max_digits=12, verbose_name='سعر الوحدة'),
        ),
    ]
