# Generated by Django 5.1.15 on 2026-06-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesinvoiceline_sale_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='العدد بوحدة البيع المختارة (قطع أو وحدات جملة).', max_digits=12, verbose_name='العدد (بالوحدة)'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='sale_unit',
            field=models.CharField(choices=[('PIECE', 'قطعة'), ('WHOLESALE', 'وحدة الجملة')], default='PIECE', help_text='تبيع بالقطعة ولا بوحدة الجملة (دستة/كرتونة حسب المنتج). الكمية والسعر بيتحسبوا على حسب الوحدة.', max_length=10, verbose_name='وحدة البيع'),
        ),
    ]
