# Generated by Django 5.1.15 on 2026-07-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_journalline_accessory'),
        ('sales', '0006_alter_salesinvoiceline_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='auto_generated',
            field=models.BooleanField(default=False, editable=False, help_text='سند اتعمل تلقائياً من فاتورة بيع نقدي.', verbose_name='اتولّد تلقائياً'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cash_account',
            field=models.ForeignKey(blank=True, help_text='لو البيع نقدي، الفلوس بتدخل هنا. سيبه فاضي عشان يستخدم حساب النقدية الافتراضي.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_sales_invoices', to='core.cashaccount', verbose_name='الخزنة/البنك (للبيع النقدي)'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('CREDIT', 'آجل (على الحساب)'), ('CASH', 'نقدي (تحصيل فوري)')], default='CREDIT', help_text='آجل = مستحق على حساب العميل. نقدي = بيتحصّل بالكامل وقت الترحيل في الخزنة/البنك.', max_length=10, verbose_name='نوع البيع'),
        ),
    ]
